name: Build and Deploy LaTeX PDF 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest  # Updated LaTeX image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Compile LaTeX (Multiple Runs for ToC)
        run: |
          xelatex -interaction=nonstopmode main.tex
          xelatex -interaction=nonstopmode main.tex  # Run twice to fix ToC issues

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4  
        with:
          name: pdf_file
          path: main.pdf

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build]

    steps:
      - name: Set variables
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Download PDF Artifact
        uses: actions/download-artifact@v4  
        with:
          name: pdf_file

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main-${{ env.DATE }}-${{ env.SHA8 }}
          release_name: "Automatic PDF Build (${{ env.DATE }})"
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main-${{ env.DATE }}-${{ env.SHA8 }}.pdf
          asset_content_type: application/pdf
